<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.103.3" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
        <PackageReference Include="Dapper" Version="2.1.86" />
        <PackageReference Include="DogStatsD-CSharp-Client" Version="9.2.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
        <PackageReference Include="OpenSkillSharp" Version="1.1.0" />
        <PackageReference Include="ppy.osu.Game" Version="2026.916.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2026.916.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2026.916.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2026.916.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2026.916.0" />
        <PackageReference Include="ppy.osu.Server.OsuQueueProcessor" Version="2026.709.0" />
        <PackageReference Include="Sentry.AspNetCore" Version="6.11.0" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="oauth-public.key" />
        <Content Include="oauth-public.key">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup Label="Code Analysis">
        <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="All" />
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)CodeAnalysis\BannedSymbols.txt" />
    </ItemGroup>

</Project>
