// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System;
using System.Linq;
using System.Threading.Tasks;
using Moq;
using osu.Server.Spectator.Database;
using osu.Server.Spectator.Database.Models;
using osu.Server.Spectator.Hubs.Multiplayer.Matchmaking.Elo;
using osu.Server.Spectator.Hubs.Multiplayer.Matchmaking.Queue;
using Xunit;

namespace osu.Server.Spectator.Tests.Matchmaking
{
    public class MatchmakingBeatmapSelectorTest
    {
        [Fact]
        public void OnlyEasyBeatmaps()
        {
            MatchmakingBeatmapSelector beatmapSelector = new MatchmakingBeatmapSelector(new matchmaking_pool(),
                Enumerable.Range(1, 1000).Select(i => new matchmaking_pool_beatmap
                {
                    beatmap_id = i,
                    rating = 1000,
                }).ToArray(), new Mock<IDatabaseFactory>().Object);

            matchmaking_pool_beatmap[] result = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.Equal(50, result.Length);

            matchmaking_pool_beatmap[] result2 = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.NotEqual(result.OrderBy(b => b.beatmap_id), result2.OrderBy(b => b.beatmap_id));
        }

        [Fact]
        public void OnlyAverageBeatmaps()
        {
            MatchmakingBeatmapSelector beatmapSelector = new MatchmakingBeatmapSelector(new matchmaking_pool(),
                Enumerable.Range(1, 1000).Select(i => new matchmaking_pool_beatmap
                {
                    beatmap_id = i,
                    rating = 1500,
                }).ToArray(), new Mock<IDatabaseFactory>().Object);

            matchmaking_pool_beatmap[] result = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.Equal(50, result.Length);

            matchmaking_pool_beatmap[] result2 = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.NotEqual(result.OrderBy(b => b.beatmap_id), result2.OrderBy(b => b.beatmap_id));
        }

        [Fact]
        public void OnlyHardBeatmaps()
        {
            MatchmakingBeatmapSelector beatmapSelector = new MatchmakingBeatmapSelector(new matchmaking_pool(),
                Enumerable.Range(1, 1000).Select(i => new matchmaking_pool_beatmap
                {
                    beatmap_id = i,
                    rating = 2000,
                }).ToArray(), new Mock<IDatabaseFactory>().Object);

            matchmaking_pool_beatmap[] result = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.Equal(50, result.Length);

            matchmaking_pool_beatmap[] result2 = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.NotEqual(result.OrderBy(b => b.beatmap_id), result2.OrderBy(b => b.beatmap_id));
        }

        [Fact]
        public void WideSelection()
        {
            MatchmakingBeatmapSelector beatmapSelector = new MatchmakingBeatmapSelector(new matchmaking_pool(),
                Enumerable.Range(1, 1000).Select(i => new matchmaking_pool_beatmap
                {
                    beatmap_id = i,
                    rating = 1000 + i,
                }).ToArray(), new Mock<IDatabaseFactory>().Object);

            matchmaking_pool_beatmap[] result = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            int countEasy = result.Count(b => b.rating < 1500);
            int countHard = result.Count(b => b.rating > 1500);

            Assert.Equal(50, result.Length);
            Assert.True((double)countEasy / result.Length >= 0.25);
            Assert.True((double)countHard / result.Length >= 0.25);

            matchmaking_pool_beatmap[] result2 = beatmapSelector.GetAppropriateBeatmaps(50, [new EloRating(1500, 80)]);
            Assert.NotEqual(result.OrderBy(b => b.beatmap_id), result2.OrderBy(b => b.beatmap_id));
        }

        [Fact]
        public void NoDuplicates()
        {
            MatchmakingBeatmapSelector selector = new MatchmakingBeatmapSelector(new matchmaking_pool(),
            [
                new matchmaking_pool_beatmap { beatmap_id = 0, rating = 1000 },
                new matchmaking_pool_beatmap { beatmap_id = 1, rating = 1000 },
            ], new Mock<IDatabaseFactory>().Object);

            matchmaking_pool_beatmap[] result = selector.GetAppropriateBeatmaps(50, [new EloRating(1000, 350), new EloRating(1000, 350)]);

            Assert.Equal(2, result.Length);
            Assert.Single(result, t => t.beatmap_id == 0);
            Assert.Single(result, t => t.beatmap_id == 1);
        }

        [Fact]
        public async Task CorrectAutoGeneratedPoolRuleset()
        {
            Mock<IDatabaseFactory> dbFactory = new Mock<IDatabaseFactory>();
            Mock<IDatabaseAccess> dbAccess = new Mock<IDatabaseAccess>();

            dbFactory.Setup(db => db.GetInstance()).Returns(dbAccess.Object);
            dbAccess.Setup(db => db.GetMatchmakingPoolBeatmapsAsync(It.IsAny<uint>())).Returns<uint>(_ => Task.FromResult(Array.Empty<matchmaking_pool_beatmap>()));
            dbAccess.Setup(db => db.GetMatchmakingGlobalPoolBeatmapsAsync(1, 0)).Returns<int, int>((rulesetId, _) => Task.FromResult(new[]
            {
                new database_beatmap
                {
                    beatmap_id = 1234,
                    playmode = (ushort)rulesetId
                }
            }));

            MatchmakingBeatmapSelector selector = await MatchmakingBeatmapSelector.Initialise(new matchmaking_pool { ruleset_id = 1 }, dbFactory.Object);
            matchmaking_pool_beatmap[] result = selector.GetAppropriateBeatmaps(50, []);

            Assert.Single(result);
            Assert.Equal(1234, result.Single().beatmap_id);
            Assert.Equal(1, result.Single().playmode);
        }
    }
}
