name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy-docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      
      - name: Generate docs
        working-directory: osu.Server.Spectator.PublicAPIDocs
        run: dotnet run --build
      
      - name: Upload generated docs as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: osu.Server.Spectator.PublicAPIDocs/_site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4